.build:
  stage: build
  image: ${BUILD_IMAGE}
  #tags:
  #  - build
  script:
    - $BUILD_SHELL
    - ls

.deploy-artifact:
  image: centos:8
  stage: deploy-artifact
  script:
    - curl -u ${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD} -T ${ARTIFACT_PATH} ${ARTIFACTORY_URL}/${ARTIFACTORY_NAME}/${TARGET_FILE_PATH}/${TARGET_ARTIFACT_NAME}
