.build:
  stage: build
  image: ${BUILD_IMAGE}
  #tags:
  #  - build
  script:
    - $BUILD_SHELL
    - ls

.deploy-artifact:
  image: centos:8
  stage: deploy-artifact
  script:
    - curl -u ${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD} -T ${ARTIFACT_PATH} ${ARTIFACTORY_URL}/${ARTIFACTORY_NAME}/${TARGET_FILE_PATH}/${TARGET_ARTIFACT_NAME}
    #- curl -u ${ARTIFACTORY_USER}:112312 -T ${ARTIFACT_PATH} ${ARTIFACTORY_URL}/${ARTIFACTORY_NAME}/${TARGET_FILE_PATH}/${TARGET_ARTIFACT_NAME}

.build-image:
  stage: build-image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$DOCKER_REGISTRY_URL\":{\"username\":\"$DOCKER_REGISTRY_USER\",\"password\":\"$DOCKER_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context "./" --dockerfile $DOCKER_FILE_PATH --destination $IMAGE_NAME
  #script:
  #  - docker login -u ${DOCKER_REGISTRY_USER} -p ${DOCKER_REGISTRY_PASSWORD} ${DOCKER_REGISTRY_URL}
  #  - docker build -t ${IMAGE_NAME} -f ${DOCKER_FILE_PATH} .
  #  - docker push ${IMAGE_NAME}
  #  - docker rmi ${IMAGE_NAME}
