.build:
  stage: build
  image: ${BUILD_IMAGE}
  #tags:
  #  - build
  script:
    - $BUILD_SHELL $BUILD_OPTS
    - ls

.deploy-artifact:
  image: centos:8
  stage: deploy-artifact
  script:
    - curl -u ${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD} -T ${ARTIFACT_PATH} ${ARTIFACTORY_URL}/${ARTIFACTORY_NAME}/${TARGET_FILE_PATH}/${TARGET_ARTIFACT_NAME}

.build-image:
  stage: build-image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$DOCKER_REGISTRY_URL\":{\"username\":\"$DOCKER_REGISTRY_USER\",\"password\":\"$DOCKER_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --skip-tls-verify --context "./" --dockerfile $DOCKER_FILE_PATH --destination $DOCKER_REGISTRY_URL/library/$IMAGE_NAME