include:
  - project: 'devops/gitlab-ci'
    ref: main
    file: 'jobs/build.yml'
  - project: 'devops/gitlab-ci'
    ref: main
    file: 'jobs/test.yml'
  - project: 'devops/gitlab-ci'
    ref: main
    file: 'jobs/code-analysis.yml'

variables:
  JUNIT_REPORT_PATH: 'target/surefire-reports/TEST-*.xml'
  CACHE_DIR: 'target/'

  BUILD_SHELL: 'mvn clean package -DskipTests'
  BUILD_IMAGE: 'maven:3.8.3-jdk-8'

  TEST_SHELL: 'mvn test'
  TEST_IMAGE: 'maven:3.8.3-jdk-8'

  SONAR_SCANNER_IMAGE: 'sonarsource/sonar-scanner-cli:4.6'
  SCAN_DIR: 'src'
  ARTIFACT_PATH: 'target/*.jar'
# 定义全局缓存
cache:
  paths:
    - ${CACHE_DIR}

stages:
  - build
  - test
  - code-analysis

build:
  stage: build
  extends: .build

test:
  stage: test
  extends: .test
  artifacts:
    reports:
      junit: ${JUNIT_REPORT_PATH}

code-analysis:
  stage: code-analysis
  extends: .code-analysis