include:
  - project: 'devops/gitlab-ci'
    ref: master
    file: 'jobs/build.yml'

variables:
  BUILD_SHELL: 'mvn clean package -DskipTests'
  CACHE_DIR: 'target/'

# 定义全局缓存
cache:
  paths:
    - ${CACHE_DIR}

stages:
  - build

build:
  stage: build
  extends: .build