include:
  - project: 'devops/gitlab-ci'
    ref: main
    file: 'jobs/build.yml'
  - project: 'devops/gitlab-ci'
    ref: main
    file: 'jobs/test.yml'

# could customize your build param here or by default as the undermentioned
variables:
  BUILD_SHELL: 'npm install && npm run build'
  CACHE_DIR: 'build/'
  BUILD_IMAGE: 'node:14.17.6-stretch-slim'

  TEST_SHELL: 'npm test'
  TEST_IMAGE: 'node:14.17.6-stretch-slim'
# 定义全局缓存
cache:
  paths:
    - ${CACHE_DIR}
    - node_modules
stages:
  - build
  - test

build:
  stage: build
  extends: .build

test:
  stage: test
  extends: .test